
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/softw/cmake-3.27.0-rc3-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19044 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/softw/cmake-3.27.0-rc3-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/softw/cmake-3.27.0-rc3-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/softw/cmake-3.27.0-rc3-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET Framework
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 10.07.2023 23:39:14.
      Project "D:\\c++\\game\\game\\CMakeFiles\\3.27.0-rc3\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\c++\\game\\game\\CMakeFiles\\3.27.0-rc3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Done Building Project "D:\\c++\\game\\game\\CMakeFiles\\3.27.0-rc3\\CompilerIdC\\CompilerIdC.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:02.11
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/c++/game/game/CMakeFiles/3.27.0-rc3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/softw/cmake-3.27.0-rc3-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/softw/cmake-3.27.0-rc3-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/softw/cmake-3.27.0-rc3-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET Framework
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 10.07.2023 23:39:17.
      Project "D:\\c++\\game\\game\\CMakeFiles\\3.27.0-rc3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\c++\\game\\game\\CMakeFiles\\3.27.0-rc3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Done Building Project "D:\\c++\\game\\game\\CMakeFiles\\3.27.0-rc3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:01.35
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/c++/game/game/CMakeFiles/3.27.0-rc3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/softw/cmake-3.27.0-rc3-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/softw/cmake-3.27.0-rc3-windows-x86_64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/c++/game/game/CMakeFiles/CMakeScratch/TryCompile-6aynxh"
      binary: "D:/c++/game/game/CMakeFiles/CMakeScratch/TryCompile-6aynxh"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/c++/game/game/CMakeFiles/CMakeScratch/TryCompile-6aynxh'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe" cmTC_ff53a.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET Framework
        Copyright (C) Microsoft Corporation. All rights reserved.
        
        Build started 10.07.2023 23:39:19.
        Project "D:\\c++\\game\\game\\CMakeFiles\\CMakeScratch\\TryCompile-6aynxh\\cmTC_ff53a.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_ff53a.dir\\Debug\\".
          Creating directory "D:\\c++\\game\\game\\CMakeFiles\\CMakeScratch\\TryCompile-6aynxh\\Debug\\".
          Creating directory "cmTC_ff53a.dir\\Debug\\cmTC_ff53a.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_ff53a.dir\\Debug\\cmTC_ff53a.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_ff53a.dir\\Debug\\\\" /Fd"cmTC_ff53a.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\softw\\cmake-3.27.0-rc3-windows-x86_64\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30133 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCCompilerABI.c
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_ff53a.dir\\Debug\\\\" /Fd"cmTC_ff53a.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\softw\\cmake-3.27.0-rc3-windows-x86_64\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\c++\\game\\game\\CMakeFiles\\CMakeScratch\\TryCompile-6aynxh\\Debug\\cmTC_ff53a.exe" /INCREMENTAL /ILK:"cmTC_ff53a.dir\\Debug\\cmTC_ff53a.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/c++/game/game/CMakeFiles/CMakeScratch/TryCompile-6aynxh/Debug/cmTC_ff53a.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/c++/game/game/CMakeFiles/CMakeScratch/TryCompile-6aynxh/Debug/cmTC_ff53a.lib" /MACHINE:X64  /machine:x64 cmTC_ff53a.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_ff53a.vcxproj -> D:\\c++\\game\\game\\CMakeFiles\\CMakeScratch\\TryCompile-6aynxh\\Debug\\cmTC_ff53a.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_ff53a.dir\\Debug\\cmTC_ff53a.tlog\\unsuccessfulbuild".
          Touching "cmTC_ff53a.dir\\Debug\\cmTC_ff53a.tlog\\cmTC_ff53a.lastbuildstate".
        Done Building Project "D:\\c++\\game\\game\\CMakeFiles\\CMakeScratch\\TryCompile-6aynxh\\cmTC_ff53a.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:01.70
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/softw/cmake-3.27.0-rc3-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/softw/cmake-3.27.0-rc3-windows-x86_64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/c++/game/game/CMakeFiles/CMakeScratch/TryCompile-txdzgo"
      binary: "D:/c++/game/game/CMakeFiles/CMakeScratch/TryCompile-txdzgo"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/c++/game/game/CMakeFiles/CMakeScratch/TryCompile-txdzgo'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe" cmTC_b00d3.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET Framework
        Copyright (C) Microsoft Corporation. All rights reserved.
        
        Build started 10.07.2023 23:39:21.
        Project "D:\\c++\\game\\game\\CMakeFiles\\CMakeScratch\\TryCompile-txdzgo\\cmTC_b00d3.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_b00d3.dir\\Debug\\".
          Creating directory "D:\\c++\\game\\game\\CMakeFiles\\CMakeScratch\\TryCompile-txdzgo\\Debug\\".
          Creating directory "cmTC_b00d3.dir\\Debug\\cmTC_b00d3.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_b00d3.dir\\Debug\\cmTC_b00d3.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_b00d3.dir\\Debug\\\\" /Fd"cmTC_b00d3.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\softw\\cmake-3.27.0-rc3-windows-x86_64\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30133 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_b00d3.dir\\Debug\\\\" /Fd"cmTC_b00d3.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\softw\\cmake-3.27.0-rc3-windows-x86_64\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\c++\\game\\game\\CMakeFiles\\CMakeScratch\\TryCompile-txdzgo\\Debug\\cmTC_b00d3.exe" /INCREMENTAL /ILK:"cmTC_b00d3.dir\\Debug\\cmTC_b00d3.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/c++/game/game/CMakeFiles/CMakeScratch/TryCompile-txdzgo/Debug/cmTC_b00d3.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/c++/game/game/CMakeFiles/CMakeScratch/TryCompile-txdzgo/Debug/cmTC_b00d3.lib" /MACHINE:X64  /machine:x64 cmTC_b00d3.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_b00d3.vcxproj -> D:\\c++\\game\\game\\CMakeFiles\\CMakeScratch\\TryCompile-txdzgo\\Debug\\cmTC_b00d3.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_b00d3.dir\\Debug\\cmTC_b00d3.tlog\\unsuccessfulbuild".
          Touching "cmTC_b00d3.dir\\Debug\\cmTC_b00d3.tlog\\cmTC_b00d3.lastbuildstate".
        Done Building Project "D:\\c++\\game\\game\\CMakeFiles\\CMakeScratch\\TryCompile-txdzgo\\cmTC_b00d3.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:01.76
        
      exitCode: 0
...
